version: "3.7"
services:
        validator-import-launchpad:
                container_name: validator-import-launchpad
                image: gcr.io/prysmaticlabs/prysm/validator:${PRYSM_DOCKER_TAG}
                command: accounts-v2 import --keys-dir="/launchpad/eth2.0-deposit-cli/validator_keys" --wallet-dir="/data/wallets" --passwords-dir="/data/passwords"
                volumes:
                        - ./validator:/data
                        - ./launchpad:/launchpad