############################################################
##
## Read up on parameters on
## https://docs.prylabs.network/docs/prysm-usage/parameters/
##
############################################################

##############
# Connectivity
beacon-rpc-provider: haproxy:14000
monitoring-host: 0.0.0.0

enable-local-protection: true

enable-external-slasher-protection: true
slasher-rpc-provider: haproxy:14002

#####################################
# Validator accounts & key management
keymanager: wallet
keymanageropts: /data/keystoreWallet.json

############
# Monitoring
enable-account-metrics: true

###########
# Fun Stuff
graffiti: ""