############################################################
##
## Read up on parameters on
## https://docs.prylabs.network/docs/prysm-usage/parameters/
##
############################################################

##############
# Connectivity
beacon-rpc-provider: beacon:4000
monitoring-host: 0.0.0.0

#####################################
# Validator accounts & key management
keymanager: wallet
keymanageropts: /data/keystoreWallet.json


###########
# Fun Stuff
graffiti: ""

medalla: yes